Layout/DotPosition:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowURI: true

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - test/**/*

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Max: 550
  Exclude:
    - config/**/*
    - test/**/*

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - test/**/*
    - db/schema.rb

Style/AsciiComments:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - vendor/**/*
    - node_modules/**/*
    - app/services/log/report/**/*

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest
  - rubocop-rake
